server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
         - id: empleado-service
          uri: lb://empleado-service
          predicates:
            - Path=/empleado/**
        
        - id: horas-extra-service
          uri: lb://horas-extra-service
          predicates:
            - Path=/horasExtra/**

        - id: justificativos-service
          uri: lb://justificativos-service
          predicates:
            - Path=/justificativo/**

         - id: marcas-reloj-service
          uri: lb://marcas-reloj-service
          predicates:
            - Path=/marcas/**
            
        - id: planilla-sueldos-service
          uri: lb://planilla-sueldos-service
          predicates:
            - Path=/planilla/**
        